server:
  port: 8080

spring:
  application:
    name: demo-langchain

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# OpenAI API 설정
openai:
  api-key: ${OPENAI_API_KEY}
  model: "gpt-4o-mini"
  temperature: 0.7

# LangChain 설정 (Chroma DB 경로)
langchain:
  chroma:
    base-url: http://localhost:8000
    collection-name: univ_embeddings

management:
  endpoints:
    web:
      exposure:
        include: health,info

ssu:
  id: ${SSU_ID}
  pw: ${SSU_PW}
